# Generated by Django 6.0.1 on 2026-01-25 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 25, 19, 1, 47, 958012, tzinfo=datetime.timezone.utc)),
        ),
    ]
